language: cpp
dist: xenial
compiler: gcc

addons: 
  apt: 
    packages: libboost-all-dev

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

# Xenial
services:
  - xvfb

script: 
  # Bouw het project
  - qmake -qt=qt5 djog_picos_2018.pro
  - make --silent debug
  # Run het een beetje
  # - ./djog_picos_2018
  # cppcheck
  - cppcheck --error-exitcode=1 . 
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov >/dev/null
  # Call OCLint
  - ./do_oclint

after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)
