#!/bin/bash
git checkout richel
git pull

for branch in bas mad-max quinn Quinn richel rohan seb tom truus
do
  git checkout $branch
  git pull
  git checkout richel
  git merge $branch
  git push
done

git checkout richel
